version: '3'

services:
    db:
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD=limesurvey_password
            - POSTGRES_DB=limesurvey_db
            - POSTGRES_USER=limesurvey_user

    limesurvey:
        build: .
        environment:
            - LIMESURVEY_PORT=8080
            - LIMESURVEY_DB_TYPE=pgsql
            - LIMESURVEY_DB_HOST=db
            - LIMESURVEY_DB_PORT=5432
            - LIMESURVEY_DB_NAME=limesurvey_db
            - LIMESURVEY_DB_TABLE_PREFIX=lime_
            - LIMESURVEY_DB_USERNAME=limesurvey_user
            - LIMESURVEY_DB_PASSWORD=limesurvey_password
            - LIMESURVEY_ADMIN_USER=limesurvey_admin
            - LIMESURVEY_ADMIN_NAME=limesurvey_admin
            - LIMESURVEY_ADMIN_EMAIL=limesurvey@limemail.com
            - LIMESURVEY_ADMIN_PASSWORD=limesurvey_admin_password
            - LIMESURVEY_URL_FORMAT=path
        ports:
            - "8081:8080"
        depends_on:
            - db
